<?php


namespace entrepotBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
use SBC\NotificationsBundle\Model\BaseNotification;
use SBC\NotificationsBundle\Builder\NotificationBuilder;

/**
 * Notification
 *
 * @ORM\Table(name="notification")
 * @ORM\Entity(repositoryClass="entrepotBundle\Repository\NotificationRepository")
 */
class Notification extends BaseNotification implements \JsonSerializable
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;


    /**
     * @ORM\Column(type="integer")
     */
    private $nbr;

    /**
     * @ORM\ManyToOne(targetEntity="Reclamation")
     * @ORM\JoinColumn(name="idreclamation",referencedColumnName="Id")
     */
    private  $idreclamation;

    /**
     * @return mixed
     */
    public function getIdreclamation()
    {
        return $this->idreclamation;
    }

    /**
     * @param mixed $idreclamation
     */
    public function setIdreclamation($idreclamation)
    {
        $this->idreclamation = $idreclamation;
    }

    /**
     * @return mixed
     */
    public function getNbr()
    {
        return $this->nbr;
    }

    /**
     * @param mixed $nbr
     */
    public function setNbr($nbr)
    {
        $this->nbr = $nbr;
    }

    public function getId()
    {
        return $this->id; // TODO: Change the autogenerated stub
    }


    public function jsonSerialize()
    {
        return get_object_vars($this);// TODO: Implement jsonSerialize() method.
    }

}